### ISSUE TITLE
TypeScript Typedefs

### ISSUE THREAD

**Issue by BierDav** [noeldelgado/parse-css-color#9]
Would be kind to have TypeScript Typedefinitions ;)

**Comment by noeldelgado** [comment]
Hi @BierDav, I just pushed a beta version for this.

Here is the PR #11.

Could you try installing `parse-css-color@0.2.2-beta.0` and see if it works for you?
(I'm not really into TS yet, so I would really appreciate your help)

**Comment by BierDav** [comment]
Looks fine can't test it right now. I'm wondering if it is better to port the whole project to typescript? I've already done so. If you want to i make a push request

**Comment by noeldelgado** [comment]
Thanks, I will merge and publish this then (I already tested it on TS and non-TS projects).
Please feel free to create a PR with the port.

**Comment by BierDav** [comment]
What is the `type` for in the result. Is this the result format or the detected source format?

**Comment by noeldelgado** [comment]
I have no idea, told you I don't do TS, this was my attempt to make the warning about types to go away.

The latest version is now published as 0.2.0, if you have time please give it a try, if there are still issue pls let me know and/or feel free to open a PR with improvements/fixes, thx

**Comment by noeldelgado** [comment]
feel free to re-open if needed
